### ISSUE TITLE
Error in face detection code

### ISSUE THREAD

**Issue by nagarajansriram** [Mjrovai/OpenCV-Face-Recognition#13]
while running face detection code
  faces = faceCascade.detectMultiScale(gray,scaleFactor=1.2,minNeighbors=5,minSize=(20,20))

got error as

error: OpenCV(4.1.0) /io/opencv/modules/objdetect/src/cascadedetect.cpp:1658: error: (-215:Assertion failed) !empty() in function 'detectMultiScale'

please help me to resolve. thanks in advance.

**Comment by Avant-Gardiste** [comment]
Probably, the XML or file is missing or the path to it is incorrect.

**Comment by vaishaliisingh** [comment]
Ensure the Correct Path to the Haar Cascade File, Verify the Haar Cascade File Exists, Handle the Case Where the Cascade File Fails to Load, Ensure OpenCV is Installed Properly, Check for Dependencies
