### ISSUE TITLE
Traceback Error

### ISSUE THREAD

**Issue by Suave101** [Mjrovai/OpenCV-Face-Recognition#15]
Traceback (most recent call last):
  File "C:... /OpenCV-Face-Recognition-master/FacialRecognition/02_face_training.py", line 21, in <module>
    recognizer = cv2.face.LBPHFaceRecognizer_create()
AttributeError: module 'cv2.cv2' has no attribute 'face'

**Comment by ShangYuChiang** [comment]
You could try this
recognizer=cv2.face.EigenFaceRecognizer_create()

**Comment by Utkarsh1504** [comment]
firstly check all the installed packages if any package is missing then install them and if all packages are installed successfully then make sure that in
C:\Python\Lib\site-packages\cv2 directory
there is a file named cv2.cp37 type file with extension .pyd is present, if is not, then install it after installing in the same directory I hope your program 'MultiObjectTracker' will run successfully.
